### ISSUE TITLE
Images Base64 encoded are not rendered

### ISSUE THREAD

**Issue by martinolivares** [kannan-ar/MariGold.OpenXHTML#11]
Steps to reproduce:

1. Use html containing an img with src = base64 image as attached

[base64 img.txt](https://github.com/kannan-ar/MariGold.OpenXHTML/files/3882528/base64.img.txt)

2. Generate doc and it doesn't render the img

**Comment by kannan-ar** [comment]
This is fixed now. Please update your nuget pack to 2.6.2
