### ISSUE TITLE
Image sizing in outputted Word document

### ISSUE THREAD

**Issue by alexanderkenney** [kannan-ar/MariGold.OpenXHTML#12]
I'm outputting a word document and applying styles to the h1, h2, h3, p and table elements. I'm also trying to set the <img /> width using css and it doesnt seem to translate into the word document. I always end up with the image displayed full size. I basically want to constrain all images to a set width so that they flow inline with the paragraphs. Any help with overriding the image sizing would be really appreciated.

**Comment by kannan-ar** [comment]
Can you please post that HTML?

**Comment by sandeepsanagapalli** [comment]
Hi In .net framework images are rendering but in .net Core I'm using the package in a Azure function strangely the Images are not rendering.

**Comment by sandeepsanagapalli** [comment]
Moreover the image size mentioned in CSS is not considered and the actual image in being drawn in .net Framework

**Comment by kannan-ar** [comment]
This is fixed in the version 3.0
