### ISSUE TITLE
Page Break issue

### ISSUE THREAD

**Issue by dkrvl** [kannan-ar/MariGold.OpenXHTML#16]
HTML to word conversion
- Used CSS `page-break-before: always;` but it is not reflecting in output word document. and there is not much documentation available for this kind of issue.

How page breaks works? Is there need any way other than CSS rules in html to breaks the page in out put word file.

Thank you for your works and efforts to make available this tool public.

**Comment by kannan-ar** [comment]
This is fixed in the version 3.0
