### ISSUE TITLE
Link to an files doesn't allow blanks

### ISSUE THREAD

**Issue by Helmut-Ortmann** [kannan-ar/MariGold.OpenXHTML#5]
Hello,

when using a blank in the file path it doesn't work. After removing blanks everything runs smooth.

Example:
`<img type="image/png" src="Feature Realisation - template - ReqIF V_000968c1/x04000000011CA34C.png" />`

Thanks,

Helmut

**Comment by kannan-ar** [comment]
Hi Helmut,

Thanks for pointing out the issue. It is now rectified and a new version of NuGet package is uploaded. Please update your package.
