### ISSUE TITLE
Licensing for this project

### ISSUE THREAD

**Issue by pgray64** [kannan-ar/MariGold.OpenXHTML#6]
Would it be possible to license this project (and MariGold.HtmlParser) with an open source license? I would like to use this library for a server side application and wanted to make sure that I was legally in the clear. 
Code hosted on Github without a license excludes both commercial and personal use for anyone except the author. 

Alternatively, could I obtain explicit permission to use this library in my project? 

Thanks

**Comment by kannan-ar** [comment]
License added
