### ISSUE TITLE
Saving a File in Track Changes mode

### ISSUE THREAD

**Issue by anirindg** [kannan-ar/MariGold.OpenXHTML#8]
Can I convert html document to .docx file in 'Track Changes' mode. That is, when I hover over the inserted/deleted text in the document, it should show which user inserted/deleted the text, at what datetime alongwith actual text?
And the actual inserted/deleted text would be identified with the help of custom tags in the html file.

Please confirm if this can be done using the current code.

Regards,

**Comment by kannan-ar** [comment]
Sorry I don't have any plan for such a feature.
