### ISSUE TITLE
images and tables are not rendered

### ISSUE THREAD

**Issue by jfaquinojr** [kannan-ar/MariGold.OpenXHTML#9]
How to reproduce:

1) Grab the html using TinyMCE
https://www.tiny.cloud/docs/demo/full-featured/

2) Generate docx

````C#
var doc = new WordDocument(filename);
doc.Process(new HtmlParser(html));
````

**Comment by kannan-ar** [comment]
Couldn't replicate the issue. Can you please send me the HTML generated from TinyMCE?

**Comment by Aless55** [comment]
@kannan-ar I am using the latest version and have the same Problem with Tables, here is my table:
```
<table>
 <tbody>
   <tr>
     <th colspan="1" rowspan="1" colwidth="260">asdasd</th>
     <th colspan="1" rowspan="1"></th>
     <th colspan="1" rowspan="1"></th>
     <th colspan="1" rowspan="1" colwidth="110"></th>
   </tr>
   <tr>
    <td colspan="1" rowspan="1" colwidth="260"></td>
    <td colspan="1" rowspan="1"> </td>
    <td colspan="1" rowspan="1"></td>
    <td colspan="1" rowspan="1" colwidth="110">{{Arbeitgeber.Hey}}</td>
  </tr>
  <tr>
    <td colspan="1" rowspan="1" colwidth="260">asxdasd </td>
    <td colspan="1" rowspan="1">asdasd</td>
    <td colspan="1" rowspan="1">asd</td>
    <td colspan="1" rowspan="1" colwidth="110">asd</td>
  </tr>
 </tbody>
</table>
```
Since I am using your code for work I would be glad if you could help me out if I did something wrong here...

**Comment by kannan-ar** [comment]
@Aless55 My apologies for the late reply. I tried to replicate your issue and couldn't find anything. See my output. Can you please specify your issue?

![image](https://user-images.githubusercontent.com/2585075/177086231-fe906f79-9477-42d2-ad22-3ab9d8592c9f.png)

**Comment by SavoInfostream** [comment]
@kannan-ar My output is similar, but why doesn't it render table borders?
